alter function public.nfos_employee_add_purchase_order_line(uuid,uuid,numeric,numeric,text) security definer;
alter function public.nfos_employee_adjust_inventory(uuid,uuid,numeric,uuid,text,text) security definer;
alter function public.nfos_employee_assign_action(text,uuid,text) security definer;
alter function public.nfos_employee_assign_production_order(uuid,uuid) security definer;
alter function public.nfos_employee_complete_batch(uuid,jsonb,jsonb,numeric,text,boolean,text) security definer;
alter function public.nfos_employee_confirm_spun_cure(uuid,text) security definer;
alter function public.nfos_employee_create_purchase_order(uuid,date,uuid,text) security definer;
alter function public.nfos_employee_create_reorder_po(uuid,date,uuid,text) security definer;
alter function public.nfos_employee_create_work_item(text,text,text,text,date,uuid,text) security definer;
alter function public.nfos_employee_get_batch_workspace(uuid) security definer;
alter function public.nfos_employee_get_inventory_workspace() security definer;
alter function public.nfos_employee_get_manager_workspace() security definer;
alter function public.nfos_employee_get_production_workspace() security definer;
alter function public.nfos_employee_get_purchasing_workspace() security definer;
alter function public.nfos_employee_receive_item(uuid,uuid,numeric,text,uuid,text,numeric,timestamp with time zone,text) security definer;
alter function public.nfos_employee_receive_purchase_order_line(uuid,numeric,text,text,timestamp with time zone,text) security definer;
alter function public.nfos_employee_record_quality_check(uuid,text,numeric,text,boolean,text) security definer;
alter function public.nfos_employee_release_batch(uuid,text) security definer;
alter function public.nfos_employee_set_batch_step_completion(uuid,uuid,boolean,text) security definer;
alter function public.nfos_employee_set_item_supplier_terms(uuid,uuid,integer,numeric,numeric,numeric,text,boolean,text) security definer;
alter function public.nfos_employee_set_spun_batch_details(uuid,text,numeric,text,text) security definer;
alter function public.nfos_employee_set_work_item_status(uuid,text,text) security definer;
alter function public.nfos_employee_start_assigned_batch(uuid,uuid,numeric,text) security definer;
alter function public.nfos_employee_submit_purchase_order(uuid) security definer;
alter function public.nfos_employee_transfer_inventory(uuid,numeric,uuid,uuid,uuid,text,text,text) security definer;
alter function public.nfos_get_employee_access() security definer;
alter function public.nfos_get_employee_work() security definer;
alter function public.nfos_get_manager_notification_summary() security definer;
alter function public.nfos_get_my_notifications() security definer;
alter function public.nfos_get_notification_preferences() security definer;
alter function public.nfos_set_notification_preferences(boolean,boolean) security definer;
alter function public.nfos_set_notification_status(uuid,text) security definer;
alter function public.nfos_sync_notifications() security definer;

grant execute on function public.nfos_sync_notifications() to service_role;
