alter function public.nfos_employee_add_purchase_order_line(uuid,uuid,numeric,numeric,text) security invoker;
alter function public.nfos_employee_adjust_inventory(uuid,uuid,numeric,uuid,text,text) security invoker;
alter function public.nfos_employee_assign_action(text,uuid,text) security invoker;
alter function public.nfos_employee_assign_production_order(uuid,uuid) security invoker;
alter function public.nfos_employee_complete_batch(uuid,jsonb,jsonb,numeric,text,boolean,text) security invoker;
alter function public.nfos_employee_confirm_spun_cure(uuid,text) security invoker;
alter function public.nfos_employee_create_purchase_order(uuid,date,uuid,text) security invoker;
alter function public.nfos_employee_create_reorder_po(uuid,date,uuid,text) security invoker;
alter function public.nfos_employee_create_work_item(text,text,text,text,date,uuid,text) security invoker;
alter function public.nfos_employee_get_batch_workspace(uuid) security invoker;
alter function public.nfos_employee_get_inventory_workspace() security invoker;
alter function public.nfos_employee_get_manager_workspace() security invoker;
alter function public.nfos_employee_get_production_workspace() security invoker;
alter function public.nfos_employee_get_purchasing_workspace() security invoker;
alter function public.nfos_employee_receive_item(uuid,uuid,numeric,text,uuid,text,numeric,timestamp with time zone,text) security invoker;
alter function public.nfos_employee_receive_purchase_order_line(uuid,numeric,text,text,timestamp with time zone,text) security invoker;
alter function public.nfos_employee_record_quality_check(uuid,text,numeric,text,boolean,text) security invoker;
alter function public.nfos_employee_release_batch(uuid,text) security invoker;
alter function public.nfos_employee_set_batch_step_completion(uuid,uuid,boolean,text) security invoker;
alter function public.nfos_employee_set_item_supplier_terms(uuid,uuid,integer,numeric,numeric,numeric,text,boolean,text) security invoker;
alter function public.nfos_employee_set_spun_batch_details(uuid,text,numeric,text,text) security invoker;
alter function public.nfos_employee_set_work_item_status(uuid,text,text) security invoker;
alter function public.nfos_employee_start_assigned_batch(uuid,uuid,numeric,text) security invoker;
alter function public.nfos_employee_submit_purchase_order(uuid) security invoker;
alter function public.nfos_employee_transfer_inventory(uuid,numeric,uuid,uuid,uuid,text,text,text) security invoker;
alter function public.nfos_get_employee_access() security invoker;
alter function public.nfos_get_employee_work() security invoker;
alter function public.nfos_get_manager_notification_summary() security invoker;
alter function public.nfos_get_my_notifications() security invoker;
alter function public.nfos_get_notification_preferences() security invoker;
alter function public.nfos_set_notification_preferences(boolean,boolean) security invoker;
alter function public.nfos_set_notification_status(uuid,text) security invoker;
alter function public.nfos_sync_notifications() security invoker;

grant usage on schema nfos_private to authenticated, service_role;

grant execute on function nfos_private.current_employee_access() to authenticated;
grant execute on function nfos_private.employee_portal_work() to authenticated;
grant execute on function nfos_private.employee_set_work_item_status(uuid,text,text) to authenticated;
grant execute on function nfos_private.employee_set_batch_step_completion(uuid,uuid,boolean,text) to authenticated;
grant execute on function nfos_private.employee_set_spun_batch_details(uuid,text,numeric,text,text) to authenticated;
grant execute on function nfos_private.employee_record_quality_check(uuid,text,numeric,text,boolean,text) to authenticated;
grant execute on function nfos_private.employee_confirm_spun_cure(uuid,text) to authenticated;
grant execute on function nfos_private.employee_receive_item(uuid,uuid,numeric,text,uuid,text,numeric,timestamptz,text) to authenticated;
grant execute on function nfos_private.employee_adjust_inventory(uuid,uuid,numeric,uuid,text,text) to authenticated;
grant execute on function nfos_private.employee_transfer_inventory(uuid,numeric,uuid,uuid,uuid,text,text,text) to authenticated;
grant execute on function nfos_private.employee_submit_purchase_order(uuid) to authenticated;
grant execute on function nfos_private.employee_receive_purchase_order_line(uuid,numeric,text,text,timestamptz,text) to authenticated;
grant execute on function nfos_private.employee_start_assigned_batch(uuid,uuid,numeric,text) to authenticated;
grant execute on function nfos_private.employee_release_batch(uuid,text) to authenticated;
grant execute on function nfos_private.employee_complete_batch(uuid,jsonb,jsonb,numeric,text,boolean,text) to authenticated;
grant execute on function nfos_private.employee_create_purchase_order(uuid,date,uuid,text) to authenticated;
grant execute on function nfos_private.employee_add_purchase_order_line(uuid,uuid,numeric,numeric,text) to authenticated;
grant execute on function nfos_private.employee_create_reorder_po(uuid,date,uuid,text) to authenticated;
grant execute on function nfos_private.employee_set_item_supplier_terms(uuid,uuid,integer,numeric,numeric,numeric,text,boolean,text) to authenticated;
grant execute on function nfos_private.employee_assign_action(text,uuid,text) to authenticated;
grant execute on function nfos_private.employee_assign_production_order(uuid,uuid) to authenticated;
grant execute on function nfos_private.employee_create_work_item(text,text,text,text,date,uuid,text) to authenticated;
grant execute on function nfos_private.employee_production_workspace() to authenticated;
grant execute on function nfos_private.employee_batch_workspace(uuid) to authenticated;
grant execute on function nfos_private.employee_inventory_workspace() to authenticated;
grant execute on function nfos_private.employee_purchasing_workspace() to authenticated;
grant execute on function nfos_private.employee_manager_workspace() to authenticated;
grant execute on function nfos_private.sync_notifications() to authenticated, service_role;
grant execute on function nfos_private.my_notifications() to authenticated;
grant execute on function nfos_private.set_notification_status(uuid,text) to authenticated;
grant execute on function nfos_private.get_notification_preferences() to authenticated;
grant execute on function nfos_private.set_notification_preferences(boolean,boolean) to authenticated;
grant execute on function nfos_private.manager_notification_summary() to authenticated;

grant execute on function public.nfos_sync_notifications() to service_role;
